# Generated by Django 4.2.6 on 2023-12-10 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.CharField(default=4, verbose_name="Review rating"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=40,
                        message="Length of the movie must be longer than 30 mins",
                    )
                ],
                verbose_name="Movie duration",
            ),
        ),
    ]
